version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: 12.x
  build:
    commands:
      #- cfn-lint -t template.yaml
      #- aws cloudformation package --template-file template.yaml --output-template-file packaged-template.yaml
      - sam build
      - sam deploy
# artifacts:
#   files:
#     - packaged-template.yaml
